version: '3.8'

services:

  app-backend:
    build: .
    container_name: aee-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DB_HOST: postgres-db
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  postgres-db:
    image: postgres:15
    container_name: aee-postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: aee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7
    container_name: aee-redis-cache
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local