#spring.datasource.url=jdbc:h2:mem:aee
#spring.datasource.username=banco
#spring.datasource.password=
#spring.datasource.driverClassName=org.h2.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://localhost:5432/aee_db
spring.datasource.username=admin
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
api.security.token.secret=apipassword123
logging.level.org.springframework.security=DEBUG
