CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255),
    qual_usuario VARCHAR(50)
);

CREATE TABLE professor (
    pessoa_id BIGINT NOT NULL PRIMARY KEY,
    CONSTRAINT fk_professor_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa(id)
);

CREATE TABLE responsavel (
    pessoa_id BIGINT NOT NULL PRIMARY KEY,
    telefone VARCHAR(255),
    CONSTRAINT fk_responsavel_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa(id)
);

CREATE TABLE aluno (
    pessoa_id BIGINT NOT NULL PRIMARY KEY,
    data_nascimento DATE,
    turma VARCHAR(255),
    diagnostico VARCHAR(255),
    professor_id BIGINT,
    responsavel_id BIGINT,
    CONSTRAINT fk_aluno_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa(id),
    CONSTRAINT fk_aluno_professor FOREIGN KEY (professor_id) REFERENCES professor(pessoa_id),
    CONSTRAINT fk_aluno_responsavel FOREIGN KEY (responsavel_id) REFERENCES responsavel(pessoa_id)
);

CREATE TABLE relatorio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_registro TIMESTAMP,
    tipo VARCHAR(50) NOT NULL,
    conteudo TEXT NOT NULL,
    aluno_id BIGINT NOT NULL,
    professor_id BIGINT NOT NULL,
    CONSTRAINT fk_relatorio_aluno FOREIGN KEY (aluno_id) REFERENCES aluno(pessoa_id),
    CONSTRAINT fk_relatorio_professor FOREIGN KEY (professor_id) REFERENCES professor(pessoa_id)
);

CREATE TABLE atividade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    data_entrega DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    observacoes TEXT,
    aluno_id BIGINT NOT NULL,
    professor_id BIGINT NOT NULL,
    CONSTRAINT fk_atividade_aluno FOREIGN KEY (aluno_id) REFERENCES aluno(pessoa_id),
    CONSTRAINT fk_atividade_professor FOREIGN KEY (professor_id) REFERENCES professor(pessoa_id)
);

CREATE TABLE pdi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicial DATE,
    data_fim DATE,
    objetivos TEXT NOT NULL,
    aluno_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_pdi_aluno FOREIGN KEY (aluno_id) REFERENCES aluno(pessoa_id)
);